# Linear Transformation
In two dimensions, a two-dimension linear transformation is a special kind of function which takes in a two-dimensional vector and outputs another two-dimensional vector. We can think of smooshing something around in space.

But must follow the geometric rule: The _origin must remain fixed_, and _all lines must remain lines_. 

Every possible input vector moves to some new output vector, or thinking about a vector as just a point in space, a linear transformation is moving some point in space to some other point. Some linear transformations are simple like rotating about the origin, others can be a bit trickier. 

You only need to record where the two basis vectors, $\hat{i}$ and $\hat{j}$ each land, and everything else will follow from that. 

**Example**: Consider the vector $\vec{v} = \left[\begin{array} -1\\ 2 \end{array}\right]$ meaning that it equals $-1\hat{i} + 2\hat{j}$. The location where $\vec{v}$ lands will be -1 times the vector where $\hat{i}$ landed plus 2 times the vector where $\hat{j}$ landed. In other words, it started off as a certain linear combination of $\hat{i}$ and $\hat{j}$ and it ends up is that same linear combination of where those two vectors landed. This means you can deduce where v must go based on where $\hat{i}$ and $\hat{j}$ each land. For the example in video 3 of 3Blue1Brown: 4:46, here we can read off that $\hat{i}$ lands on the coordinates (-1, 2). and $\hat{j}$ lands on the x-axis over at the coordinates (3, 0). This implies that the vector represented by -1 $\hat{i}$ + 2 $\hat{j}$ ends up at -1 times the vector (1, 2) + 2 times the vector (3,0)

$$ -1 \left[\begin{array} -1\\ 2 \end{array}\right] + 2\left[\begin{array} 33 \\ 0 \end{array}\right] = \left[\begin{array} 55\\ 2 \end{array}\right]$$

As long as we have a record of where $\hat{i}$ + 2 $\hat{j}$ each land, we can find where the transformed $\vec{v}$ lands. 

**In a more general coordinate space..**

$\hat{i} = \left[\begin{array} -1\\ 2 \end{array}\right]$ 
$\hat{j} = \left[\begin{array} 33\\ 0 \end{array}\right]$ 

$$ x \left[\begin{array} -1\\ 2 \end{array}\right] + y\left[\begin{array} 33 \\ 0 \end{array}\right] = \left[\begin{array} 11 x + 3y\\ -2x + 0y \end{array}\right]$$

With any input vector, we can determine where that vector lands using the above formula. Thus, a two-dimensional linear transformation is completely described by four numbers:
- two coordinates for where $\hat{i}$ lands
- two coordinates for where $\hat{j}$ lands

It is common practice to package the coordinates into a grid, called a 2-by-2 matrix describing a linear transformation. Where we can interpret the columns as the two special vectors $\hat{i}$ and $\hat{j}$ 

$\left[\begin{matrix}
    3 & 2 \\
    -2 & 1
\end{matrix}\right]$

If we are given a matrix describing some linear transformation and some vector $\vec{u}$ and you want to know where that linear transformation takes that vector, you can take the coordinates of the vector multiply them by the corresponding columns of the matrix, then add together what you get. 

**General Case**

$\left[ \begin{matrix} a & b\\ c & d \end{matrix} \right]$
$\left[ \begin{array} xx\\ y \end{array} \right]$

We get,
$x\left[ \begin{array} aa\\ c \end{array} \right] + y\left[ \begin{array} bb\\ d \end{array} \right] $
which leaves us, $\left[ \begin{matrix} ax + by\\ cx + dy \end{matrix} \right]$

**Sample Transformations**

$\mathbf{Shear} = \left[ \begin{matrix} 1 & 1\\ 0 & 1 \end{matrix} \right]$

If the vectors that $\hat{i}$ and $\hat{j}$ land on are linearly dependent (one vector is a scaled version of the other). It means that the linear transformation squishes all of 2D space on to the line where those two vectors sit, also known as the one-dimensional span of those two linearly dependent vectors. 


## Summarize

Linear transformations are a way to move around space such that grid lines remain parallel and evenly spaced and such that the origin remains fixed. These transformations can be described using only a handful of numbers. The coordinates of where each basis vector lands. Matrices give us a language to describe these transformations, where the columns represent those coordinates and matrix-vector multiplication is just a way to compute what that transformation does to a given vector. The important take-away here is that, every time you see a matrix, you can interpret it as a certain transformation of space. 

This is a main concept in Linear Algebra as once we can start to think about matrices as transformations of space, we will be able to deeply understand linear algebra and the topics to come!

In [48]:
import numpy as np

x = np.array([2, 3])
transformation = np.column_stack([[1, 2], [3, 1]])
transformation

array([[1, 3],
       [2, 1]])

In [31]:
x @ transformation

array([8, 9])

In [36]:
(x[0] * transformation[0]) + (x[1] * transformation[1])

array([8, 9])